otel.service.name=crud-otel-application
otel.traces.exporter=logging
otel.metrics.exporter=none
otel.logs.exporter=none

# Disable noise
otel.instrumentation.jdbc.enabled=false
otel.instrumentation.hibernate.enabled=false
otel.instrumentation.spring-data.enabled=false
otel.instrumentation.hikaricp.enabled=false
otel.instrumentation.runtime-telemetry.enabled=false
otel.instrumentation.jvm-metrics.enabled=false
otel.instrumentation.process-telemetry.enabled=false